#!/usr/bin/env python

# Generate one email according to params, and send to smtp server

import smtplib
import sys,os
from optparse import OptionParser

parser = OptionParser()

parser.add_option("-s", "--subject", dest="subject", default='Test message', 
                  help="Email subject")
parser.add_option("-f", "--from", dest="f", default='originator@email.com', 
                  help="From email address")
parser.add_option("-t", "--to", dest="to", default='destination@email.com', 
                  help="To email address")
parser.add_option("-H", "--host", dest="host", default='localhost', 
                  help="smtp server host")
parser.add_option("-p", "--port", dest="port", default='2526', 
                  help="smtp server port")

(options, args) = parser.parse_args()

if not sys.stdin.isatty():
	msgText = sys.stdin.read()
else:
	msgText = 'Test content'

# Import the email modules we'll need
from email.mime.text import MIMEText

msg = MIMEText(msgText)

me = '<%s>' % options.f
you = '<%s>' % options.to

msg['Subject'] = options.subject
msg['From'] = me
msg['To'] = you

# Send the message via our own SMTP server, but don't include the
# envelope header.
s = smtplib.SMTP(options.host,int(options.port))
s.sendmail(me, [you], msg.as_string())
s.quit()
